testSF/force-app/main/default/objects/Book__c/fields/Active_Lendings__c.field-meta.xml
<CustomField>
    <fullName>Active_Lendings__c</fullName>
    <label>Active Lendings</label>
    <summaryFilterItems>
        <field>Lending__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Lending__c.Book__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

testSF/force-app/main/default/objects/Book__c/fields/Total_Number_of_Copies__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Copies__c</fullName>
    <label>Total Number of Copies</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

testSF/force-app/main/default/objects/Lending__c/Lending__c.object-meta.xml
<CustomObject>
    <label>Lending</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Lending Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

testSF/force-app/main/default/objects/Lending__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Lendings</relationshipLabel>
    <relationshipName>Lendings1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

testSF/force-app/main/default/objects/Library__c/Library__c.object-meta.xml
<CustomObject>
    <label>Library</label>
    <nameField>
        <label>Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

testSF/force-app/main/default/classes/testBookAvailabilityLending.cls
@isTest
public class testBookAvailabilityLending {
    
    @isTest
    static void testLendingInsert() {
        Library__c library = new Library__c(Name='Library');
        insert library;
        
        Book__c book = new Book__c(Name = 'Test Book', Library__c = library.Id, Total_Number_of_Copies__c = 10);
        insert book;
        
        Lending__c lending = new Lending__c(Book__c = book.Id,	Start_date__c=Date.today());
        insert lending;
        
        Book__c updatedBook = [SELECT Active_Lendings__c FROM Book__c WHERE Id = :book.Id];
        System.assertEquals(1, updatedBook.Active_Lendings__c);
    }
}