testSF/force-app/main/default/objects/Book__c/fields/Availables_copies__c.field-meta.xml
<CustomField>
    <fullName>Availables_copies__c</fullName>
    <formula>Total_Number_of_Copies__c  -  Active_Lendings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Availables copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

testSF/force-app/main/default/objects/Book__c/fields/Total_Number_of_Copies__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Copies__c</fullName>
    <label>Total Number of Copies</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

testSF/force-app/main/default/objects/Library__c/Library__c.object-meta.xml
<CustomObject>
    <label>Library</label>
    <nameField>
        <label>Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

testSF/force-app/main/default/classes/LibraryBooksController.cls
public with sharing class LibraryBooksController {
    
    
    @AuraEnabled
    public static List<Book__c> getBooksForLibrary(String libraryId) {
        try {
            return [SELECT Id, Name, Total_Number_of_Copies__c, Availables_copies__c FROM Book__c WHERE Library__c = :libraryId ORDER BY Name];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}