testSF/force-app/main/default/objects/Library__c/Library__c.object-meta.xml
<CustomObject>
    <label>Library</label>
    <nameField>
        <label>Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

testSF/force-app/main/default/objects/Library_user__c/Library_user__c.object-meta.xml
<CustomObject>
    <label>Library user</label>
    <nameField>
        <displayFormat>User-{0000}</displayFormat>
        <label>Library user Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

testSF/force-app/main/default/objects/Library_user__c/fields/Library__c.field-meta.xml
<CustomField>
    <fullName>Library__c</fullName>
    <label>Library</label>
    <referenceTo>Library__c</referenceTo>
    <relationshipLabel>Library users</relationshipLabel>
    <relationshipName>Library_users1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

testSF/force-app/main/default/objects/Library_user__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Library_users</relationshipName>
    <type>Lookup</type>
</CustomField>

testSF/force-app/main/default/objects/User/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
            <value>
                <fullName>/not specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

testSF/force-app/main/default/classes/LibraryUsersController.cls
public with sharing class LibraryUsersController {
    
    @AuraEnabled
    public static List<User> getLibraryUsers(String libraryId) {
        try {
            return [SELECT Id, Name, Email,Gender__c FROM User WHERE Id IN (SELECT User__c FROM Library_User__c WHERE Library__c = :libraryId) ORDER BY Name];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}